<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <div class="qty-holder">
            <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
            <div class="qty-changer">
                <a href="javascript:void(0)" class="qty_inc"><i class="icon-up-dir"></i></a>
                <a href="javascript:void(0)" class="qty_dec"><i class="icon-down-dir"></i></a>
            </div>
        </div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="if (validateLimit() == true){productAddToCartForm.submit(this);}else{}"><span><span><i class="icon-cart"></i><?php echo $buttonTitle ?></span></span></button>
        <span id='ajax_loader' style='display:none'><i class="ajax-loader small animate-spin"></i></span>
		<?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
<script>
		function validateLimit(){
			var qty = 0;
			var limit = 0;
			jQuery('.inner-wrapper> .mini-products-list li', parent.document.body).each(function(i,e){
				if (typeof jQuery(e).data('qty') !== "undefined"){ 
					qty += (jQuery(e).data('qty'));
				}
			});
			jQuery('.inner-wrapper> .mini-products-list li', parent.document.body).each(function(i,e){
				if (typeof jQuery(e).data('planLimit') !== "undefined"){
					limit += (jQuery(e).data('planLimit'));
				} 
			});
			if (limit == 0){
				group_id = <?php echo Mage::getSingleton('customer/session')->getCustomerGroupId(); ?>;
				if (group_id !== 4){
					alert('You must select a Subscription Plan and Membership options first');
					return false;
				}
			}
			console.log(qty+' '+limit);
			if ( limit != 0 && (qty+1) > limit) {
				alert('Amount exceed, if you want more, please switch to another plan.');
				return false;
			} else {
				return true;
			}
		}
</script>