<?php
/**
 * @category    Zalw
 * @package     Zalw_Mssgext
 * @author      Zalw
 * @use	   	This .phtml file shows send message form to admin and the grid of send messages to admin  
 */
?>

<div class="post">
	
<!--send messag form-->   
<div class="mess">
 <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
 </div>
<div class="send-message">

    <form action="<?php echo Mage::getBaseUrl();?>advancemsg/manage/sendmessage/" method="post" id="form-validate">

        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Send Message') ?></h2>
           			<div class="field">
            <?php echo $this->__('Subject') ?><label class="required" for="subject"><em>*</em></label>
                <div class="input-box">
                   	<input type="text" class="input-text required-entry messagetitle" id="messagetitle" name="messagetitle" />
             </div>
				 </div>
				 <div class="field">
						<?php echo $this->__('Message') ?><label class="required" for="subject"><em>*</em></label>
							<div class="input-box send_item_text">
								<textarea class="input-text required-entry message" id="message" name="message" rows=3 cols=80></textarea>	
						 </div>
				 </div>
				 </br>
				 <div class="field">
				<input id="template_attachment" name="template_attachment" value="" type="file">  
				</div>
			<div class="buttons-set">
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>
				 <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
			</div>
        </div>

    </form>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('messagegrid') ?>
</div>

<script type="text/javascript">
//<![CDATA[
    var salesagentForm = new VarienForm('form-validate', true);
//]]>
</script>
<?php ?>