<?php $menuHelper = Mage::helper('megamenu'); ?>
<?php $only_categories = $this->getOnlyCategories(); ?>
<div class="mobile-nav side-block container">
    <div class="menu-all-pages-container">
        <ul class="menu">
						<li class="menu-item get-started-menu" style="list-style:none;">
					<a href="//www.abrameals.com/get-started.html">Get Started</a>
				</li>
            <?php echo $menuHelper->getMobileMenuContent($only_categories); ?>
        </ul>
    </div>
</div>
<div class="mobile-nav-overlay close-mobile-nav"></div>