<div class="mini-cart">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal())
    ?>
    <?php $_items = $this->getRecentItems() ?>
		
    <!--<a href="javascript:void(0)" class="mybag-link"><i class="icon-mini-cart"></i><span class="cart-info"><span class="cart-qty"><?php echo $_cartQty ?></span><span><?php echo $this->__('item(s)') ?></span></span></a>-->
		<button class="collapse">CART</button>
		<div class="sidebarContainer">
        <div class="topCartContent block-content theme-border-color" >
            <div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
                <?php $_items = $this->getRecentItems() ?>
                <?php if(count($_items)): ?>
                    <ol class="mini-products-list">
					<?php $hasItem = True; ?>
					<?php $item_price_total = 0; ?>
                        <?php 	$_items = array_reverse($_items);
								foreach($_items as $_item): ?>
                            <?php echo $this->getItemHtml($_item);
								//TODO: 
							 $item_price_total += $_item->getBasePrice();
							?>
                        <?php endforeach; ?>
                    </ol>
                    <div class="totals">
                        <span class="label"><?php echo $this->__('Total')?>: </span>
						<?php   ?>

                        <span class="price-total">
						<?php echo Mage::helper('core')->currency($item_price_total,true,false);//$_subtotal ?>

						</span>
                    </div>
                    <div class="actions">
                       <!-- <a class="btn btn-default" href="<?php echo $this->getUrl('checkout/cart'); ?>"><i class="icon-basket"></i><?php echo $this->__('View Cart') ?></a>  -->
					   <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <a style="text-align:center
						" id="btn-checkout-confirm" class="btn btn-default" href="<?php echo $this->getCheckoutUrl(); ?>"><i class="icon-right-thin"></i><?php echo $this->__('Checkout') ?></a>
						<div class="checkout-fail-notice">
						amount exceed</div>
                <?php endif; ?>
                        <div class="clearer"></div>
                    </div>
                <?php else: ?>
                    <p class="cart-empty">
                        <?php echo $this->__('You have no items in your shopping cart.'); ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
		
<script type="text/javascript">
    /*
	jQuery(function($){
        $('.mini-cart').mouseover(function(e){
            $(this).children('.topCartContent').fadeIn(200);
            return false;
        }).mouseleave(function(e){
            $(this).children('.topCartContent').fadeOut(200);
            return false;
        });
    });
	*/ 
	var hasItem = <?php if ($hasItem == True){echo 1;}
						else{ echo 0;}		?>;
	
	//hide on all other than membership,subscription and menu pages by Ron 6/14/2016
	jQuery(function($){
		$(".collapse").click(function(){
			$(".topCartContent").css("display","block");
			$(this).hide;
		});
		$(".topCartContent").mouseleave(function(){
			$(this).slideUp( "slow", function() {});
			$(".collapse").css("display","block");
		});

	
		if (( $('.category-subscription-plans').length > 0 || $('.category-menu').length > 0 )&& hasItem == 1)  {
			$('.topCartContent').show();
			$('.collapse').show();
		}
		else{
			$('.topCartContent').hide();
			$('.collapse').hide();
		}

         //check if user select enough meals, if not stop proceeding to checkout page
        $('#btn-checkout-confirm').click(function(e){
            var qty = 0;
            var limit = 0;
            jQuery('.inner-wrapper> .mini-products-list li', parent.document.body).each(function(i,e){
                if (typeof jQuery(e).data('qty') !== "undefined"){ 
                    qty += (jQuery(e).data('qty'));
                }
            });
            jQuery('.inner-wrapper> .mini-products-list li', parent.document.body).each(function(i,e){
                if (typeof jQuery(e).data('planLimit') !== "undefined"){
                    limit += (jQuery(e).data('planLimit'));
                } 
            });
            if(limit == 0){
                group_id = <?php echo Mage::getSingleton('customer/session')->getCustomerGroupId(); ?>;
                if (group_id !== 4){
                    e.preventDefault();
                    alert('You must select a Subscription Plan and Membership options first');
                }
            }
            if (qty != limit) {
                e.preventDefault();
                var unselected = limit - qty;
                alert('You have '+ unselected+' more meals to select.');
            }
            
        });
	});


</script> </div>
</div>