<?php
$advancemsgCheck = Mage::getStoreConfig('advancemsg_section/advancemsg_group/enabled');
if ( $advancemsgCheck == '1'){ 
    if($this->getNewMessageNotification()){?>
        <ul class="messages">
            <li class="notice-msg">
                <span style="color:#eb5e00;">
                    <strong>Advance Message Notification : </strong>
                </span>
                <?php echo $this->getNewMessageNotification();?>
                <span>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl("advancemsg/adminhtml_manage/log/") ?>" >Click Here</a> to view message.
                </span>
            </li>
        </ul>
<?php } } ?>