
<?php $customer = Mage::getSingleton('customer/session')->getCustomer();
$groupId = $customer->getGroupId();

if( Mage::getSingleton('customer/session')->isLoggedIn() and $groupId != 4){ ?>

	<div class="step-title">
				Step4: </div> <div class="title-description" >Contents... </div>
				
	<h4>
	<?php  ?>
	<?php $pref_str = $_GET['pref']; ?>
	<?php if ($pref_str != ''){ ?>
	
	<?php 	if ($pref_str != 'none' && $pref_str != 'none/'){ ?>
	According to your preference: 
	<?php	$pref = explode(",", $pref_str);
				//print_r ($pref); 
				foreach($pref as $p){
					$attr_model = Mage::getResourceModel('eav/entity_attribute_collection');
					 $p = preg_replace("/\//","",$p);
					 $attr = $attr_model->setCodeFilter($p)->getFirstItem()->getData('frontend_label');
					print_r($attr);
					print_r( ', ');
				}
					
				?>
				these meals are available to you: &nbsp;&nbsp;
				<a href="/menu.html?&pref=none" >Show All Meals </a>
	</h4>
	<?php 	} else { ?>
	<h4> You might want to go back to choose your preferences if you wish <a href="/get-started.html">Click Here</a></h4>
	<?php }}
	} elseif ($groupId == 4)  { ?>

	<h4> The following meals are filtered by your account preference:
		
<?php		foreach ($customer->getData() as $k => $v){
				//echo $k . ' ' . $v . '<br>';
				if (strpos($k, 'preference_') !== False){
					if ($v == 1){
						echo Mage::getResourceModel('eav/entity_attribute_collection')->setCodeFilter($k)->getFirstItem()->getData('frontend_label') . ', ';
						//array_push($customer_pref, $k);
					}
				}
			}
			//print_r ($customer_pref);
		?>if you want to change it  <a href="/customer/account/edit/">Click Here</a></h4>
		

<?php } ?>
		<?php if ($_GET['redirect_method'] == 'menu_add_suggested_plans'){ ?>
		<div class="dashboard" style="padding:10px;">
			<div class="welcome-msg" style="font-weidht:600; text-align:center">Please choose your own meal and checkout if you don't like our default selection in your email.</div>
		</div>
		<?php } ?>