<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Shippo Setup')?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Get me started!</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="setup_form" name="setup_form" method="post" action="<?=$this->getUrl('*/*/post')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Credentials')?></h4>
        <p>In order to make your orders available in Shippo we need to allow it to access your orders. We'll set this up for you, simply confirm and submit this form.</p>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Allow Shippo to import my orders')?> <span class="required">*</span></td>
                    <td class="input-ele"><input type="checkbox" class="checkbox required-entry" name="confirm" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('setup_form');
</script>

