<?php $menuHelper = Mage::helper('megamenu'); ?>
<div class="mobile-nav side-block container">
    <div class="close-mobile-nav close-block">Navigation</div>
    <div class="menu-all-pages-container">
        <ul class="menu">
				<li class="menu-item get-started-menu" style="list-style:none;">
					<a href="//www.abrameals.com/get-started.html">Get Started</a>
				</li>
            <?php echo $menuHelper->getMobileMenuContent(); ?>
        </ul>
    </div>
</div>